ci: update nvm config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,30 +90,34 @@ defaults_configure_nvm: &defaults_configure_nvm
   name: Configure NVM
   command: |
     cd $HOME
-
     export ENV_DOT_PROFILE=$HOME/.profile
     touch $ENV_DOT_PROFILE
-
-    echo "1. Export env variable"
-    export NVM_DIR="$HOME/.nvm"
+    echo "1. Check/Set NVM_DIR env variable"
+    if [ -z "$NVM_DIR" ]; then
+      export NVM_DIR="$HOME/.nvm"
+      echo "==> NVM_DIR has been exported - $NVM_DIR"
+    else
+      echo "==> NVM_DIR already exists - $NVM_DIR"
+    fi
+    echo "2. Check/Set NVMRC_VERSION env variable"
     if [ -z "$NVMRC_VERSION" ]; then
       echo "==> Configuring NVMRC_VERSION!"
       export NVMRC_VERSION=$(cat $CIRCLE_WORKING_DIRECTORY/.nvmrc)
       echo "export NVMRC_VERSION=$NVMRC_VERSION" >> $ENV_DOT_PROFILE
     fi
-
-    if [ -f "$NVM_DIR" ]; then
-      echo "==> $NVM_DIR exists. Skipping steps 2-4!"
-    else 
-      echo "==> $NVM_DIR does not exists. Executing steps 2-4!"
-
-      echo "2. Installing NVM"
+    echo "3. Configure NVM"
+    ## Lets check if an existing NVM_DIR exists, if it does lets skil
+    if [ -e "$NVM_DIR" ]; then
+      echo "==> $NVM_DIR exists. Skipping steps 3!"
+      # echo "5. Executing $NVM_DIR/nvm.sh"
+      # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+    else
+      echo "==> $NVM_DIR does not exists. Executing steps 4-5!"
+      echo "4. Installing NVM"
       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
-
-      echo "3. Executing $NVM_DIR/nvm.sh"
+      echo "5. Executing $NVM_DIR/nvm.sh"
       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
     fi
-
     ## Ref: https://github.com/nvm-sh/nvm/issues/1102#issuecomment-550572252
     if [ ! -z "$NVM_ARCH_UNOFFICIAL_OVERRIDE" ]; then
       echo "==> Handle NVM_ARCH_UNOFFICIAL_OVERRIDE=$NVM_ARCH_UNOFFICIAL_OVERRIDE!"
@@ -121,13 +125,17 @@ defaults_configure_nvm: &defaults_configure_nvm
       echo "export NVM_NODEJS_ORG_MIRROR=https://unofficial-builds.nodejs.org/download/release" >> $ENV_DOT_PROFILE
       source $ENV_DOT_PROFILE
     fi
-
-    echo "4. Installing Node version: $NVMRC_VERSION"
-    nvm install $NVMRC_VERSION
-    nvm alias default $NVMRC_VERSION
-    nvm use $NVMRC_VERSION
-
-    cd $CIRCLE_WORKING_DIRECTORY
+    echo "6. Setup Node version"
+    if [ -n "$NVMRC_VERSION" ]; then
+      echo "==> Installing Node version: $NVMRC_VERSION"
+      nvm install $NVMRC_VERSION
+      nvm alias default $NVMRC_VERSION
+      nvm use $NVMRC_VERSION
+      cd $CIRCLE_WORKING_DIRECTORY
+    else
+      echo "==> ERROR - NVMRC_VERSION has not been set! - NVMRC_VERSION: $NVMRC_VERSION"
+      exit 1
+    fi
 
 defaults_display_versions: &defaults_display_versions
   name: Display Versions
@@ -322,6 +330,9 @@ jobs:
 
             ## Check straight away to see if any containers have exited
             docker-compose ps
+
+            # Set Node version to default (Note: this is needed on Ubuntu)
+            nvm use default
 
             ## wait for services to be up and running
             npm run wait-4-docker
@@ -523,7 +534,7 @@ jobs:
       - setup_remote_docker
       - checkout
       - run:
-          <<: *defaults_configure_nvmrc
+          <<: *defaults_configure_nvm
       - run:
           <<: *defaults_display_versions
       - run:
@@ -547,7 +558,6 @@ jobs:
             apk --no-cache add curl
             apk --no-cache add openssh-client
             apk add --no-cache -t build-dependencies make gcc g++ python3 libtool autoconf automake
-            npm config set unsafe-perm true
             npm install -g node-gyp
       - run:
           name: Install AWS CLI dependencies
